### PR TITLE
Beginning a feature to add notes to exercises.

### PR DESCRIPTION
**Pull request by raven-black-dream**
New Feature:

Add comments to exercises on a workout.

### CODE REVIEW

**Comment by raven-black-dream** [comment]
@AkiliDaniels @katland 

I am trying to add a feature which allows the user to add a comment to an exercise in a workout. I would like your feedback on the following question.

Should the exercise note be linked to the workout, or to the mesocycle? 

I am thinking through the data model, and the requisite code which would need to be written.

If the exercise note carries through the mesocycle, that would equate to one comment per exercise per meso which would be edited, if changes are made to it. The benefit of this is that the code needed to manage this would be relatively straight forward. It would only require adding code to get any exercise notes for the exercises in the workout with the current mesocycle. 

If the exercise note is tied instead to the workout, then I would need to add the comment to the next workout as well as get any exercise notes for each workout.

What do you think?

**Comment by katland** [comment]
It sounds like you want the note to persist and apply to future workouts (ex. reminder to self about this form element), as opposed to an option for a comment on how a very specific thing on a given day went (ex. preferred machine was out of service today). In that context, linking to a mesocycle makes more sense.

**Comment by raven-black-dream** [comment]
Realistically, I am thinking about both sorts.of comment.

"Machine was broken today." But also things like "#4 on the Hoist Seated Dip Machine" (Because the Hoist machines are weird about what the number means)

**Comment by AkiliDaniels** [comment]
Yeah, linking to the whole mesocycle would be fine if it's editable, that way I could add things like "on <date> wrist was borked" or "on <date> machine was broken, changed exercise to <blah>" so if that's easier to do it makes enough sense to me for it to work

**Comment by raven-black-dream** [comment]
Probably, linking on the workout with an option to continue the note across the meso is the better move.

**Pull request merged**
